version: '3'

services: 
  backend:
    container_name: django_server
    build:
      context: ./backend/
    ports:
      - 8000:8000
    volumes:
      - ./backend/app:/backend/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"